### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by reubenhwk**
I've made a few commits aimed at reducing some of the complexity of the code.  It's just a bit of getting my feet wet in your code, but it's a start.  Please review and feel free to leave comments.

### CODE REVIEW

**Comment by ldo** [comment]
Nothing there that I want right now, sorry.

See comments on individual commits for why.

**Comment by ShabbyX** [comment]
I came here from [this comment](http://lwn.net/Articles/628254/).

@Ido, `goto` is not evil as you may have been told. It's just a tool that needs expertise. I have been a teacher assistant many years and like my predecessors, I have told my students to never use `goto`. That's because a novice C programmer doesn't have enough experience to know when `goto` makes code cleaner and when it makes spaghetti code.

This pull request does actually cleans up your code. Knowing how I used to program then and now, I can see some elements I have come to use to improve in my own code.

One is the blank lines. 20 lines of text one after the other is not as readable as one that has blank lines that separate logically related code.

For example, you could have:

```C
int f(int a, void *b)
{
    int result = 0;
    int temp;
    if (a == 0 || b == NULL)
        return -1;
    temp = *(int *)b / a;
    temp = ((temp & 0xFF) << 8) || ((temp & 0xFF00) >> 8);
    return temp;
}
```

Or you could have:

```C
int f(int a, void *b)
{
    int result = 0;
    int temp;

    if (a == 0 || b == NULL)
        return -1;

    temp = *(int *)b / a;
    temp = ((temp & 0xFF) << 8) || ((temp & 0xFF00) >> 8);

    return temp;
}
```

Which clearly distinguishes "Declarations", "Error Checking", "Computations" and "End" of the function. If more complex, you could do even better by adding comments to each section that is not obvious:

```C
int f(int a, void *b)
{
    int result = 0;
    int temp;

    /* input sanity checks */
    if (a == 0 || b == NULL)
        return -1;

    /* calculate output based on formula ... */
    temp = *(int *)b / a;
    temp = ((temp & 0xFF) << 8) || ((temp & 0xFF00) >> 8);

    return temp;
}
```

Another improve is `goto` for error recovery. Imagine this code:

```C
struct table_element
{
    int key;
    int value;
};

struct table_element *read_table(char *file_name, size_t *table_size)
{
    FILE *fin = NULL;
    struct table_element *table = NULL;
    if (file_name == NULL || table_size == NULL)
        return NULL;
    do
    {
        fin = fopen(file_name, "r");
        if (fin == NULL)
            break;
        do
        {
            bool error = false;
            if (fscanf(fin, "%zu", table_size) != 1)
                break;
            table = malloc(*table_size * sizeof *table);
            if (table == NULL)
                break;
            do
            {
                for (size_t i = 0; i < *table_size && !error; ++i)
                    if (fscanf(fin, "%d %d", &table[i].key, &table[i].value) != 2)
                    {
                        error = true;
                        break;
                    }
                if (error)
                    break;
                /* More stuff on the table, such as sanity check etc */
            } while (false);
            if (error)
            {
                free(table);
                table = NULL;
            }
        } while (false);
        fclose(fin);
    } while (false);
    return table;
}
```

And compare it with the same code written with `goto`:

```C
struct table_element
{
    int key;
    int value;
};

struct table_element *read_table(char *file_name, size_t *table_size)
{
    FILE *fin = NULL;
    struct table_element *table = NULL;

    if (file_name == NULL || table_size == NULL)
        return NULL;

    fin = fopen(file_name, "r");
    if (fin == NULL)
        goto exit_no_file;

    if (fscanf(fin, "%zu", table_size) != 1)
        goto exit_bad_table_size;

    table = malloc(*table_size * sizeof *table);
    if (table == NULL)
        goto exit_no_mem;

    for (size_t i = 0; i < *table_size && !error; ++i)
        if (fscanf(fin, "%d %d", &table[i].key, &table[i].value) != 2)
            goto exit_bad_file_format

    /* More stuff on the table, such as sanity check etc */

    goto exit_good;

exit_bad_file_format:
    free(table);

exit_no_mem:
exit_bad_table_size;
exit_good:
    fclose(fin);

exit_no_file:
    return table;
}
```

Do you see how _much_ clearer it is with `goto`? Do you see that `do { } while(false)` not only clutters the code and adds unnecessary indentation, but is also meaningless? It looks like a loop, but it only runs once. You say `break` out of the loop, but you weren't actually looping. It's actually meaningless.

On the other hand, what does `goto exit_no_mem;` tell you? It tells you that the function needs to exit because there is no memory. Can you get any more readable than _that_?

What's more, the function has become smaller even though it now has many blank lines and a few redundant labels just for clarity. That's because by trying to avoid `goto`s, you artifically try to put constructs (such as `do {} while(false)`) to work around the missing functionality.

So please, if your policy is "NO GOTOS" because that's a sin you should not even dare speak of, that only shows you are not experienced enough in C. I seriously suggest you give this some thought, and try to judge without prejudice which piece of code looks easier to read.

**Comment by reubenhwk** [comment]
goto exit_good;
I think I'd try to shorten this a bit...

exit_bad_file_format:
    free(table);

exit_no_mem:
exit_bad_table_size;
exit_good:
    fclose(fin);

exit_no_file:
    return table;


...like so...

    retval = table;
cleanup:
    if (retval != table)
        free(table);
    if (fin)
        fclose(fin);

    return retval;

**Comment by ShabbyX** [comment]
@reubenhwk , yes, that's actually what I would have normally done. I was trying to make a point though; that you can use labels to show your intent and even be verbose about it and the result is a readable code.

Of course, in real-life I would have used a couple of helper functions that don't make this just cleaner, but also more extensible in the future.

**Comment by reubenhwk** [comment]
Right on!  :)

**Comment by reubenhwk** [comment]
BTW, ldo, libpng accepted the patch so your commented out code should work in the next rev of libpng1.7..

**Pull request closed without merging**
